-- MySQL Script generated by MySQL Workbench
-- Thu Sep 19 21:08:19 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Table `mydb`.`Operator`
-- -----------------------------------------------------
CREATE TABLE `Operator` (
  `ID` INT NOT NULL,
  `First_Name` VARCHAR(45) NULL,
  `Family_Name` VARCHAR(45) NULL,
  `Date_Of_Birth` DATE NULL,
  `Drone_License` TINYINT NULL,
  `Rescue_Endorsement` BOOLEAN NULL,
  `Operations` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Drones`
-- -----------------------------------------------------
CREATE TABLE `Drones` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Class Type` TINYINT NULL,
  `Rescue` BOOLEAN NULL,
  `Operator ID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ID_idx` (`Operator ID` ASC),
  CONSTRAINT `Operator ID`
    FOREIGN KEY (`Operator ID`)
    REFERENCES `Operator` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
